---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages
    package:
      name:
      - htop
      - tmux

  - name: copy wallpaper file
    copy:
      src: files/wallpaper.jpg
      dest: usr/share/backgrounds/pop/ansible-wallpaper.jpg
      owner: root
      group: root


  - name: set wallpaper
    become_user: andreas
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file://usr/share/backgrounds/pop/ansible-wallpaper.jpg'"


  - name: set wallpaper position
    become_user: andreas
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: copy .bashrc file
    copy:
      src: files/bashrc
      dest: /home/andreas/.bashrc
      owner: andreas
      group: andreas

